accounts/urls.py
from django.urls import path

from .views import SignUpView

app_name = 'accounts'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

backoffice/urls.py
from django.urls import path

from .views import BackofficeSuggestionListView, SuggestionDeleteView

app_name = 'backoffice'
urlpatterns = [
    path('/suggestion/<int:pk>/delete/', SuggestionDeleteView.as_view(), name='suggestion_delete'),
    path('', BackofficeSuggestionListView.as_view(), name='home'),
]

suggestion/urls.py
from django.urls import path

from .views import SuggestionListView, SuggestionDetailView, SuggestionCreateView

app_name = 'suggestion'
urlpatterns = [
    path('suggestion/new/', SuggestionCreateView.as_view(), name='suggestion_new'),
    path('suggestion/<int:pk>/', SuggestionDetailView.as_view(), name='suggestion_detail'),
    path('', SuggestionListView.as_view(), name='home'),
]

web_portal_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),  # Django need to be first
    path('accounts/', include('accounts.urls')),
    path('', include('suggestion.urls')),
    path('backoffice', include('backoffice.urls'))
]

accounts/models.py
from django.db import models

# Create your models here.

backoffice/models.py
from django.db import models

# Create your models here.

suggestion/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


class Suggestion(models.Model):
    SUGGESTION = 'SUG'
    REPORT = 'REP'
    OTHERS = 'OTH'

    TYPE_CHOICES = [
        (SUGGESTION, 'Suggestion'),
        (REPORT, 'Report'),
        (OTHERS, 'Others'),
    ]

    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.EmailField(max_length=80)

    type = models.CharField(max_length=3, choices=TYPE_CHOICES, default=OTHERS)
    topic = models.CharField(max_length=60)
    body = models.TextField(max_length=1000)

    pub_date = models.DateTimeField(default=timezone.now())
    deleted = models.BooleanField(default=False)

    def __str__(self):
        return self.body[:40]

    def get_absolute_url(self):  # goes to suggestion_detail.html page
        return reverse('suggestion:suggestion_detail', args=[str(self.id)])

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

backoffice/views.py
from django.views.generic.edit import DeleteView
from django.views.generic import ListView, DetailView
from django.urls import reverse_lazy

from suggestion.models import Suggestion


class BackofficeSuggestionListView(ListView):
    queryset = Suggestion.objects.all()
    template_name = 'backoffice/home.html'
    context_object_name = 'suggestions'


class SuggestionDeleteView(DeleteView):
    model = Suggestion
    template_name = 'backoffice/suggestion_delete.html'
    success_url = reverse_lazy('suggestion:home')  # FIXME FILIPE ISTO PODE IR PARA A PAGINA GERAL DO BACKOFFICE

suggestion/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView
from django.urls import reverse_lazy

from .models import Suggestion


class SuggestionListView(ListView):
    queryset = Suggestion.objects.all()
    template_name = 'suggestion/home.html'
    context_object_name = 'suggestions'


class SuggestionDetailView(DetailView):
    model = Suggestion
    template_name = 'suggestion/suggestion_detail.html'
    context_object_name = 'suggestion'


class SuggestionCreateView(CreateView):
    model = Suggestion
    template_name = 'suggestion/suggestion_new.html'
    fields = ['first_name', 'last_name', 'email', 'type', 'topic', 'body']

templates/backoffice/home.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    {% for suggestion in suggestions %}
        <div class="">
            <h2><a href="{% url 'suggestion:suggestion_detail' suggestion.pk %}">{{ suggestion.topic }}</a></h2>
            <p>{{ suggestion.body }}</p>
        </div>
    {% endfor %}
{% endblock content %}

templates/backoffice/suggestion_delete.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>Delete post</h1>

    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ suggestion.topic }}"?</p>
        <input type="submit" value="Confirm" />
    </form>
{% endblock content %}

templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Tonicapp Web Portal</title>
    </head>
    <body>
    <header>
        <!-- Bootsrap CDN -->
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <!-- Google Fonts -->
        <link rel="stylesheet" id="avia-google-webfont" href="//fonts.googleapis.com/css?family=Open+Sans:400,600" type="text/css" media="all">

        <!-- Custom css -->
        <link href="{% static 'css/base/base.css' %}" rel="stylesheet">
    </header>
    <div>
        {% include 'base/header.html' %}

        {% if user.is_authenticated %}
            <p>Hi {{ user.username }}!</p>
            <p><a href="{% url 'logout' %}">Log out</a></p>
        {% else %}
            <p>You are not logged in.</p>
            <a href="{% url 'login' %}">Log In</a>
        {% endif %}

        {% block content %}
        {% endblock content %}
    </div>

    <!-- Scripts -->
    <!-- Bootsrap CDN -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
  </body>
</html>

templates/base/header.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'suggestion:home' %}">
        <img src='{% static "images/general/logo.png" %}' width="40" height="40" alt="">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'suggestion:suggestion_new' %}">Criar <span class="sr-only">(current)</span></a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'backoffice:home' %}">Backoffice <span class="sr-only">(current)</span></a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/suggestion/home.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    {% for suggestion in suggestions %}
        <div class="">
            <h2><a href="{% url 'suggestion:suggestion_detail' suggestion.pk %}">{{ suggestion.topic }}</a></h2>
            <p>{{ suggestion.body }}</p>
        </div>
    {% endfor %}
{% endblock content %}

templates/suggestion/suggestion_detail.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
    <div class="">
        <h2>
            <a href="{% url 'backoffice:suggestion_delete' suggestion.pk %}"> {{ suggestion.topic }}</a>
        </h2>
        {{ suggestion.title }}
        <p>{{ suggestion.body }}</p>
        <p>{{ suggestion.first_name }}</p>
        <p>{{ suggestion.last_name }}</p>
        <p>{{ suggestion.type }}</p>
        <p>{{ suggestion.email }}</p>
        <p>{{ suggestion.pub_date }}</p>
  </div>

{% endblock content %}

templates/suggestion/suggestion_new.html
{% extends 'base/base.html' %}

{% block content %}
    <h1>New Suggestion</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" />
    </form>
{% endblock %}